### PR TITLE
prune() race condition fix

### PR DESCRIPTION
**Pull request by raltnoeder**
This is supposed to be a better fix than the previously proposed one, since it avoids pruning events that have been updated by any of the 3 poll cycles before the current poll cycle (still provided that timestamps provided by drbdsetup make sense, and in the case where no events are seen, drbdtop's internal time reference isn't far ahead of drbdsetup's time).

### CODE REVIEW

**Comment by rck** [comment]
Sorry for forgetting about this one. If this is still an issue (I guess so), it would be great if you could:

- rebase the patch on current "develop" branch
- rewrite the commit msg. Yours is one very long line. Guess you forgot about the short one-liner?

Then just force push it to your `ra/punefix2` branch and I will pick it up

**Comment by raltnoeder** [comment]
Alright, should be ready some time on Monday!

**Comment by raltnoeder** [comment]
Looks like I'm a bit slow... anyway, it should be ready now.
`ra/prunefix2` on my fork

**Comment by rck** [comment]
Thanks Robert, I merged and pushed it to `origin/develop`. Guess we can then release that very soon.

**Pull request closed without merging**
